version: "3.2"

services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    expose:
      - 8000
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    build: ./nginx
    ports:
      - 9000:80
    depends_on:
      - backend

volumes:
  postgres_data:
