# Generated by Django 3.2.8 on 2021-12-10 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('partition_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_id', models.UUIDField()),
                ('index', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('TEXT_PIC_TEXT', 'text_pic_text'), ('TEXT_PIC', 'text_pic'), ('PIC_TEXT', 'pic_text'), ('TEXT_PIC_TASK', 'text_pic_task'), ('TEXT_TASK', 'text_task'), ('PIC_TASK', 'pic_task')], max_length=255)),
                ('including_task', models.BooleanField(default=False)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartitionTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('partition_id', models.UUIDField()),
                ('task_question', models.TextField()),
                ('task_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('usercourse_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('course_id', models.UUIDField()),
                ('index_progress', models.IntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
                ('partitions_completed', models.ManyToManyField(to='course_application.Partition')),
            ],
        ),
    ]
