# Generated by Django 3.2.8 on 2021-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='partitions_completed',
            field=models.ManyToManyField(blank=True, to='course_application.Partition'),
        ),
    ]
