# Generated by Django 3.2.8 on 2021-12-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_application', '0002_alter_usercourse_partitions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
