# Generated by Django 3.2.8 on 2021-12-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_application', '0004_partition_next_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='next_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
