export const authConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAIL: "GET_USER_FAIL",
    FEEDBACK_SEND_SUCCESS: "FEEDBACK_SEND_SUCCESS",
    FEEDBACK_SEND_FAIL: "FEEDBACK_SEND_FAIL",
    FEEDBACK_GET_SUCCESS: "FEEDBACK_GET_SUCCESS",
    FEEDBACK_GET_FAIL: "FEEDBACK_GET_FAIL"
}