# Generated by Django 3.2.8 on 2021-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashNews',
            fields=[
                ('dn_id', models.UUIDField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
