# Generated by Django 3.2.8 on 2021-11-20 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('desk_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('desk_id', models.UUIDField(default=uuid.uuid4)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
