# Generated by Django 3.2.8 on 2021-11-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_application', '0002_userdesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='desc_id',
            new_name='desk_id',
        ),
    ]
