# Generated by Django 3.2.8 on 2021-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_application', '0003_rename_desc_id_desk_desk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
