# Generated by Django 3.2.8 on 2021-11-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_application', '0004_desk_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='desc_id',
            new_name='desk_id',
        ),
    ]
